version: '3.8'

services:

  db:
    image: postgres
    restart: always
    environment:
      - HOSTNAME=${HOSTNAME}
      - DB_USERNAME=${DB_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${DB_NAME}
    container_name: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - '5432'
    networks:
      - app-network

  server:
    build: ./server
    container_name: server
    environment:
      - PORT=${SERVER_PORT}
      - HOSTNAME=${HOSTNAME}
      - DB_USERNAME=${DB_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SERVER_REDIRECT_URI=${SERVER_REDIRECT_URI}
      - SERVER_TOKEN_CLIENT_ID=${SERVER_TOKEN_CLIENT_ID}
      - SERVER_TOKEN_CLIENT_SECRET=${SERVER_TOKEN_CLIENT_SECRET}
    ports:
      - '3001:3001'
    depends_on:
      - db
    volumes:
      - ./server/src:/srv/app/admin-server/src
    networks:
      - app-network

  client:
    build: ./client
    container_name: client
    depends_on:
      - server
    ports:
      - '3000:3000'
    volumes:
      - ./client/app:/srv/app/admin-client/app
      # -./client:/app/
      # - ./client/public:/srv/app/admin-client/public
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN}
      - PGADMIN_DEFAULT_PASSWORD=${PG_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: