import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react';

type RootLayoutProps = {
  children: React.ReactNode;
};


const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// }


const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
	return (
	  <html lang="en">
		<head>
		  <meta charSet="utf-8" />
		  <meta name="viewport" content="width=device-width, initial-scale=1" />
		  <title>Transcendance</title>
		  {/* <link rel="icon" href="./meditation.png" /> */}
		  {/* <style>{inter}</style> */}
		</head>
		<body>{children}</body>
	  </html>
	);
  };
export default RootLayout;